name: dog_breed
description: A dog breed classifier

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  tflite: ^1.1.1
  image_picker: ^0.6.7+9
  splashscreen: ^1.2.0
  cupertino_icons: ^1.0.0
  liquid_swipe: ^1.5.0
  provider: ^4.0.4
  flutter_svg: ^0.19.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/

  fonts:
    - family: Billy
      fonts:
        - asset: assets/font.ttf


